### PR TITLE
add camel-jcifs

### PR DESCRIPTION
**Pull request by bebbo**
migrate from 2.x to 3.x

it's working for me - maybe you can use it.

### CODE REVIEW

**Comment by gautric** [comment]
@bebbo thx

**Comment by S-Thenmozhi** [comment]
@bebbo We need camel-jcifs with camel 3.x support. I tried building latest version of camel-jcifs from here but getting test failures(13 test failures) as below. please help me to understand this or am i missing something. Thanks in advance.

 testPollFileAndShouldBeMoved(org.apacheextras.camel.component.jcifs.FromSmbMoveFileTest): Failed to create route route9: Route(route9)[From[smb://WORKGROUP;joed@localhost/share/came... because of Failed to resolve endpoint: smb://WORKGROUP;joed@localhost/share/camel/FromSmbMoveFileTest?consumer.delay=5000&move=done%2Fsub2%2F%24%7Bfile%3Aname%7D.old&password=xxxxxx due to: Failed to resolve endpoint: smb://WORKGROUP;joed@localhost/share/camel/FromSmbMoveFileTest?consumer.delay=5000&move=done%2Fsub2%2F%24%7Bfile%3Aname%7D.old&password=xxxxxx due to: There are 2 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{consumer.delay=5000, password=secret123}]

**Comment by bebbo** [comment]
> @bebbo We need camel-jcifs with camel 3.x support. I tried building latest version of camel-jcifs from here but getting test failures(13 test failures) as below. please help me to understand this or am i missing something. Thanks in advance.
> 
> ...
> Unknown parameters=[{consumer.delay=5000, password=secret123}]


`password`: you have to specify the password in the url:
```
smb://[<domain>;]user:password@server/path
```

`consumer.delay`: there is no `consumer.delay` - perhaps you mean `delay` ?

**Comment by S-Thenmozhi** [comment]
> > @bebbo We need camel-jcifs with camel 3.x support. I tried building latest version of camel-jcifs from here but getting test failures(13 test failures) as below. please help me to understand this or am i missing something. Thanks in advance.
> > ...
> > Unknown parameters=[{consumer.delay=5000, password=secret123}]
> 
> `password`: you have to specify the password in the url:
> 
> ```
> smb://[<domain>;]user:password@server/path
> ```
> 
> `consumer.delay`: there is no `consumer.delay` - perhaps you mean `delay` ?

@bebbo  Thanks. It worked, password have to be in the URL and yes, it is delay not consumer.delay. Really appreciate your help. Now facing the other error as below,

FromFileToSmbTest.testFromFileToSmb:98->CamelTestSupport.assertMockEndpointsSatisfied:1059 mock://result Received message count. Expected: <2> but was: <0>

**Comment by S-Thenmozhi** [comment]
@bebbo any other branch/pull request has these changes updated(password in uri and consumer.delay) as i could see all the test cases are in the old format.  And still facing test failures as below, 
FromFileToSmbTest.testFromFileToSmb:98->CamelTestSupport.assertMockEndpointsSatisfied:1059 mock://result Received message count. Expected: <2> but was: <0>
Any help would be appreciated. Thanks!

**Comment by bebbo** [comment]
> @bebbo any other branch/pull request has these changes updated(password in uri and consumer.delay) as i could see all the test cases are in the old format. And still facing test failures as below, FromFileToSmbTest.testFromFileToSmb:98->CamelTestSupport.assertMockEndpointsSatisfied:1059 mock://result Received message count. Expected: <2> but was: <0> Any help would be appreciated. Thanks!

This camel-jcifs is working for me and reads/writes properly from/to a share as desired.
You are on your own with these tests.

**Pull request merged**
