### PR TITLE
Added statement name

### PR DESCRIPTION
**Pull request by Fabryprog**
it's equal to route.getId() consumer

### CODE REVIEW

**Comment by ullgren** [comment]
[CAMEX-76](https://camel-extra.atlassian.net/browse/CAMEX-76)

**Comment by ullgren** [comment]
I'm not sure about this implementation.  To be honest I'm not sure how the original implementation was suppose to work.

From what I can see when a `EsperConsumer` first is created it will get the statement created and maintained by the `EsperEndpoint`. This statement will then actually be shared between all consumers. If that statement is then destroyed the consumers will create there own statements and manage these separately.

With these changes the first initial statement will not have the route id as name. This will only be in effect after the initial statement was destroyed once.

To me it seems that the initial code was designed so that all `EsperConsumer` should share the same `EPStatement` instance handled by the `EsperEndpoint` but at some point some inconsistency was introduced. Where the `EsperConsumer`started to create there own statements. If this is the desired behaviour then perhaps we should remove the statement handling from the `EsperEndpoint` altogether.

Also should this not also be done for the `EsperPollingConsumer` ?

**Comment by Fabryprog** [comment]
Hello, when you create an esper statement i have Always an routeid. So... It is only to help camel's user to debug esper statement using esper metric queries. Into esper metric query result i have some informations to statement distinct by name. Today using current camel implementation i cannot set statement name and the metric are lameds!

**Comment by ullgren** [comment]
Yes but in EsperEndpoint the statement is created without a name. This "nameless" statement is then passed to the consumer in the constructor. It is then used by the consumer until destroyed at which point the consumer creates a new statement. Now naming it with route id. 

So what is the purpose of the statement created and hold by the EsperEndpoint class?

**Comment by Fabryprog** [comment]
@ullgren You're asking me why the statement is inside the endpoint or what use my fix?

I already explained that to have the name statement is a good thing for debugging at runtime. And 'an addition that involves not think anything in functionality

**Comment by ullgren** [comment]
No I'm asking if your fix really does what we think it does or if we will break anything by changing the behaviour. 

Looking at the original code the `EsperConsumer` will really uses a EsperStatment that is [created in the `EsperEndpoint` ](https://github.com/camel-extra/camel-extra/blob/master/components/camel-esper/src/main/java/org/apacheextras/camel/component/esper/EsperEndpoint.java#L78) where no name is given. This statement is a [shared statement that will be used by all consumers](https://github.com/camel-extra/camel-extra/blob/master/components/camel-esper/src/main/java/org/apacheextras/camel/component/esper/EsperEndpoint.java#L91-L95) created by that endpoint as long as it is not destroyed. The `EsperEndpoint` even has a counter to make sure it is not destroyed [until the last consumer is removed](https://github.com/camel-extra/camel-extra/blob/master/components/camel-esper/src/main/java/org/apacheextras/camel/component/esper/EsperEndpoint.java#L108-L111).

So if each consumer should start creating it's own statements. Then the code to manage the statement in `EsperEndpoint` should be removed.

Also to complete this feature the same naming of statements should be done in the `EsperPollingConsumer`.

**Comment by Fabryprog** [comment]
my idea was to make the fix less invasive as possible. Can i refactoring statement creation code?

**Comment by ullgren** [comment]
Yes I think it is better that we refactor the statement creation code than having code that does not make sense. However perhaps it would be better to name the statements using the endpoint name instead of the route id since a endpoint could possibly be used in multiple routes.

Something like what is done on the producer.

// Pontus

**Comment by Fabryprog** [comment]
So.. 

can you create 2.18.0 release? thnkx

**Comment by ullgren** [comment]
I will try to get a 2.18 out after the holidays. However there is some problems with some of the infrastructure that blocks doing the releases properly.

**Comment by Fabryprog** [comment]
@ullgren can you create 2.18.0 release? 

:-)

**Comment by ullgren** [comment]
Hi,
Unfortunately the karaf integration tests are not working properly and that should/must be fixed before we can do a release. Any help with this is welcome since I seem unable to find the root cause.

https://camel-extra.ci.cloudbees.com/job/Camel%20Extra%20master/258/

**Comment by Fabryprog** [comment]
@ullgren i haven't access to your link!

**Comment by ullgren** [comment]
I have reprovisioned the jenkins instance now should be up again soon

**Comment by ullgren** [comment]
Finally got the karad integration tests to run, well mostly.

Esper and Virtualbox itest on karaf is still failing but I think this is good enough to cut a new release.

If Jenkins builds on master goes well I will start cutting a 2.18.0 and 2.19.0 release tomorrow.

**Pull request merged**
