### PR TITLE
added new feature mapBody

### PR DESCRIPTION
**Pull request by Fabryprog**
Added new feature to esper consumer.

According to oldest mapEvents param, now you can use mapBody param to add a map using endpoint name.

Example in my test file!

### CODE REVIEW

**Comment by ullgren** [comment]
Could you please rebase this PR to match the current master.

**Comment by Fabryprog** [comment]
Now is ok!

**Comment by ullgren** [comment]
Just a thought about this row 
   `getEsperRuntime().sendEvent((Map)body, this.endpoint.getName());`
in EsperProducer.java would it make more sence to use 
   `getEsperRuntime().sendEvent(in.getBody(Map.class), this.endpoint.getName());`
To make use of camels typeconverters and in this way allow for implicit convertion of the body to a Map if it is not already ?

**Comment by Fabryprog** [comment]
So..... i must insert the assert "instanceof map"

**Comment by ullgren** [comment]
No in.getBody(Map.class) will do that for you. Simply casting the body to the desired type if it already is of hat type. If not it will look for a [type converter ](http://camel.apache.org/type-converter.html) to transform the body into the requested type.

**Comment by Fabryprog** [comment]
I know.... But i am thinking that it also is right check body instance type.

**Comment by Fabryprog** [comment]
@ullgren can you valide this pull request? is it ok?

**Comment by ullgren** [comment]
Looks good yes. I have not had time to merge it. Will get some time later this week so it will be merged before the weekend.

**Comment by Fabryprog** [comment]
Ok... this PR and this https://github.com/camel-extra/camel-extra/pull/11 are latest. It is ready to release!

**Pull request merged**
